[build]
  base = "frontend"
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_API_URL = "https://automotive-assistant-backend.railway.app"
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "https://automotive-assistant-backend.railway.app/api/:splat"
  status = 200
  force = true

[functions]
  directory = "functions"